<?php
/**
 * Disclosure notice for AI-written text: the automatic note on posts, the
 * shortcode, the block, the excerpt and feed variants and the JSON-LD node.
 *
 * One render path for every surface, so the wording an editor configures
 * applies everywhere at once, including blocks placed months ago.
 *
 * @package   TransparAI
 * @author    Patrick Schlesinger
 * @copyright 2026 Patrick Schlesinger
 * @license   GPL-2.0-or-later https://www.gnu.org/licenses/gpl-2.0.html
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Text disclosure output.
 */
final class TransparAI_Notice {

	public const BLOCK  = 'transparai/notice';
	public const MARKER = 'trai-notice';

	/**
	 * Posts whose note a template already printed in this request.
	 *
	 * @var array<int, true>
	 */
	private static array $placed = array();

	/**
	 * Tell the automatic note that a template printed the note itself.
	 */
	public static function mark_placed( int $post_id ): void {
		self::$placed[ $post_id ] = true;
	}

	/**
	 * Register hooks.
	 */
	public static function init(): void {
		/*
		 * Priority 30: after wpautop and shortcodes (10, 11) and after the badge
		 * wrap at 20, so the note is added around finished HTML and never lands
		 * inside an image wrapper. Still ahead of builder filters at 99 and
		 * later, which expect their own markup to be the last touch.
		 */
		add_filter( 'the_content', array( self::class, 'filter_content' ), 30 );
		add_filter( 'get_the_excerpt', array( self::class, 'filter_excerpt' ), 20, 2 );

		/* Feeds carry no stylesheet, so they get plain text, not the styled note. */
		add_filter( 'the_content_feed', array( self::class, 'filter_content_feed' ), 20 );
		add_filter( 'the_excerpt_rss', array( self::class, 'filter_excerpt_rss' ), 20 );
		add_action( 'rss2_item', array( self::class, 'rss_item' ) );

		/* Optional title badge in the loop and [AI] prefix on feed item titles. */
		add_filter( 'the_title', array( self::class, 'filter_title' ), 20, 2 );
		add_filter( 'the_title_rss', array( self::class, 'filter_title_rss' ), 20 );

		add_shortcode( 'transparai_notice', array( self::class, 'shortcode' ) );
		add_action( 'init', array( self::class, 'register_block' ) );
		add_action( 'enqueue_block_editor_assets', array( self::class, 'localize_block_editor' ) );
	}

	/* ---------------------------------------------------------------------
	 * Text
	 * ------------------------------------------------------------------- */

	/**
	 * The resolved note for a post, or '' when its text is not AI-written.
	 *
	 * @param int    $post_id Post ID.
	 * @param string $level   Level to render for; empty = the post's stored level.
	 */
	public static function text( int $post_id, string $level = '' ): string {
		if ( '' === $level ) {
			$level = TransparAI_Meta::get_content_level( $post_id );
		}
		if ( ! TransparAI_Meta::level_is_ai( $level ) ) {
			return '';
		}

		$text = TransparAI_Options::get( 'content_notice_text' );
		if ( '' === $text ) {
			$text = self::default_text( $level );
		}

		if ( TransparAI_Meta::LEVEL_REVIEWED === $level && TransparAI_Options::enabled( 'content_show_reviewer' ) ) {
			$stamp = TransparAI_Meta::content_review( $post_id );
			if ( null !== $stamp ) {
				$name = '' !== $stamp['responsible'] ? $stamp['responsible'] : $stamp['by'];
				$date = function_exists( 'date_i18n' ) ? date_i18n( (string) get_option( 'date_format', 'Y-m-d' ), (int) strtotime( $stamp['on'] ) ) : $stamp['on'];
				if ( '' !== $name ) {
					/* translators: 1: name of the reviewer, 2: review date. */
					$text .= ' ' . sprintf( __( 'Reviewed by %1$s on %2$s.', 'transparai' ), $name, $date );
				}
			}
		}

		/**
		 * Filters the disclosure note of a post.
		 *
		 * @param string $text    Plain-text note.
		 * @param int    $post_id Post ID.
		 * @param string $level   Disclosure level.
		 */
		return (string) apply_filters( 'transparai_notice_text', $text, $post_id, $level );
	}

	/**
	 * Translated default wording per level.
	 */
	public static function default_text( string $level ): string {
		switch ( $level ) {
			case TransparAI_Meta::LEVEL_ASSISTED:
				return __( 'This text was created with the help of AI.', 'transparai' );
			case TransparAI_Meta::LEVEL_REVIEWED:
				return __( 'This text was generated by AI and reviewed by a person.', 'transparai' );
			default:
				return __( 'This text was generated by AI.', 'transparai' );
		}
	}

	/**
	 * Human-readable level names (admin lists, editor, settings).
	 *
	 * @return array<string, string>
	 */
	public static function level_labels(): array {
		return array(
			''                              => __( 'Not classified', 'transparai' ),
			TransparAI_Meta::LEVEL_NONE     => __( 'No AI used', 'transparai' ),
			TransparAI_Meta::LEVEL_ASSISTED => __( 'AI-assisted', 'transparai' ),
			TransparAI_Meta::LEVEL_GEN      => __( 'AI-generated', 'transparai' ),
			TransparAI_Meta::LEVEL_REVIEWED => __( 'AI-generated, reviewed by a person', 'transparai' ),
		);
	}

	/* ---------------------------------------------------------------------
	 * Markup
	 * ------------------------------------------------------------------- */

	public const VARIANTS = array( 'block', 'inline', 'banner', 'badge', 'modal' );

	/**
	 * The note element. Inline and badge variants are spans (a div inside a
	 * paragraph is invalid HTML and splits the paragraph); block and banner
	 * are divs, the banner with a dismiss button; modal is a button that
	 * opens a native dialog.
	 *
	 * @param array{text?:string, variant?:string, type?:string, class?:string} $args Text, variant, content|media|systems, extra classes.
	 */
	public static function render( array $args ): string {
		$text = trim( (string) ( $args['text'] ?? '' ) );
		if ( '' === $text ) {
			return '';
		}
		$variant = (string) ( $args['variant'] ?? 'block' );
		if ( ! in_array( $variant, self::VARIANTS, true ) ) {
			$variant = 'block';
		}
		$type  = in_array( $args['type'] ?? '', array( 'media', 'systems' ), true ) ? (string) $args['type'] : 'content';
		$class = self::MARKER . ' ' . self::MARKER . '--' . $variant . ' ' . self::MARKER . '--' . $type;
		if ( ! empty( $args['class'] ) ) {
			$class .= ' ' . (string) $args['class'];
		}
		$class = esc_attr( trim( $class ) );
		switch ( $variant ) {
			case 'inline':
			case 'badge':
				$html = '<span class="' . $class . '" role="note">' . esc_html( $text ) . '</span>';
				break;
			case 'banner':
				$html = '<div class="' . $class . '" role="note"><span class="trai-notice-text">' . esc_html( $text ) . '</span>'
					. '<button type="button" class="trai-notice-dismiss" aria-label="' . esc_attr__( 'Dismiss this notice', 'transparai' ) . '">&times;</button></div>';
				break;
			case 'modal':
				$html = '<div class="' . $class . '"><button type="button" class="trai-notice-open">' . esc_html__( 'AI notice', 'transparai' ) . '</button>'
					. '<dialog class="trai-notice-dialog" role="note"><p>' . esc_html( $text ) . '</p>'
					. '<button type="button" class="trai-notice-close">' . esc_html__( 'Close', 'transparai' ) . '</button></dialog></div>';
				break;
			default:
				$html = '<div class="' . $class . '" role="note">' . esc_html( $text ) . '</div>';
		}

		/* The note can appear with the badge switched off; late enqueues print in the footer. */
		if ( function_exists( 'wp_enqueue_style' ) && ! is_admin() ) {
			wp_enqueue_style( 'transparai-front', TRANSPARAI_PLUGIN_URL . 'assets/css/front.css', array(), TRANSPARAI_VERSION );
			if ( in_array( $variant, array( 'banner', 'modal' ), true ) ) {
				wp_enqueue_script( 'transparai-front', TRANSPARAI_PLUGIN_URL . 'assets/js/front.js', array(), TRANSPARAI_VERSION, true );
			}
		}

		/**
		 * Filters the rendered note.
		 *
		 * @param string $html Note HTML.
		 * @param array  $args Render arguments.
		 */
		return (string) apply_filters( 'transparai_notice_html', $html, $args );
	}

	/**
	 * Automatic note on singular AI-written posts.
	 *
	 * @param string|mixed $content Content HTML.
	 * @return string|mixed
	 */
	public static function filter_content( $content ) {
		if ( ! is_string( $content ) || is_admin() || is_feed() ) {
			return $content;
		}
		if ( ! is_singular() || ! in_the_loop() || ! is_main_query() || doing_filter( 'get_the_excerpt' ) ) {
			return $content;
		}
		$post_id = (int) get_the_ID();
		if ( isset( self::$placed[ $post_id ] ) ) {
			return $content;
		}
		$text = self::text( $post_id );
		if ( '' === $text ) {
			return $content;
		}
		/*
		 * A placed block or shortcode is the editor's own placement; the
		 * automatic note steps back. has_block() reads the raw post content, a
		 * plain mention of the class name in a tutorial does not count, the
		 * rendered marker catches synced patterns has_block() cannot see into.
		 */
		if ( has_block( self::BLOCK, $post_id ) || str_contains( $content, 'class="' . self::MARKER . ' ' ) ) {
			return $content;
		}
		$style = TransparAI_Options::get( 'content_notice_style' );
		$html  = self::render(
			array(
				'text'    => $text,
				'variant' => $style,
			)
		);
		/* Span variants need a block of their own between blocks, or a constrained theme layout leaves them at the edge. */
		if ( '' !== $html && in_array( $style, array( 'inline', 'badge' ), true ) ) {
			$html = '<p class="trai-notice-wrap">' . $html . '</p>';
		}
		return self::place( $content, $html );
	}

	/**
	 * Put the note ahead of, after, or on both sides of the content.
	 */
	private static function place( string $content, string $note ): string {
		$position = TransparAI_Options::get( 'content_notice_position' );
		if ( 'after' === $position ) {
			return $content . $note;
		}
		if ( 'both' === $position ) {
			return $note . $content . $note;
		}
		return $note . $content;
	}

	/**
	 * Small "AI" badge behind the title of AI-written posts, in the loop
	 * only (menus and widgets print titles too, but outside the loop or
	 * for another id). Opt-in: the badge is markup inside the title.
	 *
	 * @param string|mixed $title   Title.
	 * @param int|mixed    $post_id Post ID.
	 * @return string|mixed
	 */
	public static function filter_title( $title, $post_id = 0 ) {
		if ( ! is_string( $title ) || is_admin() || is_feed() || ! TransparAI_Options::enabled( 'content_title_badge' ) ) {
			return $title;
		}
		$post_id = (int) $post_id;
		if ( $post_id <= 0 || ! in_the_loop() || $post_id !== (int) get_the_ID() ) {
			return $title;
		}
		if ( str_contains( $title, 'trai-title-badge' ) || ! TransparAI_Meta::level_is_ai( TransparAI_Meta::get_content_level( $post_id ) ) ) {
			return $title;
		}
		return $title . ' <span class="' . esc_attr( self::MARKER . ' ' . self::MARKER . '--badge trai-title-badge' ) . '" role="note">' . esc_html__( 'AI', 'transparai' ) . '</span>';
	}

	/**
	 * [AI] in front of feed item titles of AI-written posts (opt-in).
	 *
	 * @param string|mixed $title Feed title.
	 * @return string|mixed
	 */
	public static function filter_title_rss( $title ) {
		if ( ! is_string( $title ) || ! TransparAI_Options::enabled( 'feed_title_prefix' ) ) {
			return $title;
		}
		if ( ! TransparAI_Meta::level_is_ai( TransparAI_Meta::get_content_level( (int) get_the_ID() ) ) || str_starts_with( $title, '[AI] ' ) ) {
			return $title;
		}
		return '[AI] ' . $title;
	}

	/**
	 * Plain-text line on excerpts (archive teasers, related-post widgets).
	 *
	 * @param string|mixed $excerpt Excerpt.
	 * @param WP_Post|mixed $post   Post.
	 * @return string|mixed
	 */
	public static function filter_excerpt( $excerpt, $post = null ) {
		if ( ! is_string( $excerpt ) || is_admin() || is_feed() || ! TransparAI_Options::enabled( 'content_excerpt_notice' ) ) {
			return $excerpt;
		}
		$post_id = $post instanceof WP_Post ? (int) $post->ID : (int) get_the_ID();
		$text    = self::text( $post_id );
		if ( '' === $text || str_contains( $excerpt, $text ) ) {
			return $excerpt;
		}
		return rtrim( $excerpt ) . ( '' === trim( $excerpt ) ? '' : ' ' ) . $text;
	}

	/* ---------------------------------------------------------------------
	 * Feeds
	 * ------------------------------------------------------------------- */

	/**
	 * Note as a paragraph in the feed content.
	 *
	 * @param string|mixed $content Feed content HTML.
	 * @return string|mixed
	 */
	public static function filter_content_feed( $content ) {
		if ( ! is_string( $content ) || ! TransparAI_Options::enabled( 'feed_notice' ) ) {
			return $content;
		}
		$text = self::text( (int) get_the_ID() );
		if ( '' === $text || str_contains( $content, $text ) ) {
			return $content;
		}
		return self::place( $content, '<p>' . esc_html( $text ) . '</p>' );
	}

	/**
	 * Note appended to the feed excerpt (plain text).
	 *
	 * @param string|mixed $excerpt Feed excerpt.
	 * @return string|mixed
	 */
	public static function filter_excerpt_rss( $excerpt ) {
		if ( ! is_string( $excerpt ) || ! TransparAI_Options::enabled( 'feed_notice' ) ) {
			return $excerpt;
		}
		$text = self::text( (int) get_the_ID() );
		if ( '' === $text || str_contains( $excerpt, $text ) ) {
			return $excerpt;
		}
		return rtrim( $excerpt ) . ( '' === trim( $excerpt ) ? '' : ' ' ) . esc_html( $text );
	}

	/**
	 * Machine-readable feed element. WordPress declares the Dublin Core
	 * namespace in every RSS 2.0 feed, so no namespace of our own is needed
	 * and every aggregator already knows the element.
	 */
	public static function rss_item(): void {
		if ( ! TransparAI_Options::enabled( 'feed_notice' ) ) {
			return;
		}
		$text = self::text( (int) get_the_ID() );
		if ( '' !== $text ) {
			echo "\t\t<dc:description>" . esc_xml( $text ) . "</dc:description>\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- esc_xml() is the XML escaper.
		}
	}

	/* ---------------------------------------------------------------------
	 * Shortcode and block
	 * ------------------------------------------------------------------- */

	/**
	 * `[transparai_notice type="content|media|systems" style="block|inline|banner|badge|modal" text="" id=""]`.
	 *
	 * Placing the shortcode is the editor's decision to show the note, so it
	 * renders regardless of the automatic note. It still never states what is
	 * not declared: a media id without label, or a post without level, gives
	 * an empty string.
	 *
	 * @param array<string, string>|string $atts Shortcode attributes.
	 */
	public static function shortcode( $atts ): string {
		$atts = shortcode_atts(
			array(
				'type'  => 'content',
				'style' => '',
				'text'  => '',
				'id'    => '',
			),
			is_array( $atts ) ? $atts : array(),
			'transparai_notice'
		);
		$type = in_array( $atts['type'], array( 'media', 'systems' ), true ) ? $atts['type'] : 'content';
		/* A media label sits next to an image inside running text: inline by default. */
		if ( '' === $atts['style'] ) {
			$atts['style'] = 'media' === $type ? 'inline' : 'block';
		}
		$id   = (int) $atts['id'];
		$text = sanitize_text_field( (string) $atts['text'] );

		if ( 'systems' === $type ) {
			$systems = class_exists( 'TransparAI_Systems' ) ? TransparAI_Systems::visible() : array();
			if ( array() === $systems ) {
				return '';
			}
			if ( '' === $text ) {
				$text = TransparAI_Systems::notice_text( $systems );
			}
		} elseif ( 'media' === $type ) {
			if ( $id <= 0 || ! TransparAI_Meta::is_flagged( $id ) ) {
				return '';
			}
			if ( '' === $text ) {
				$text = TransparAI_Frontend::badge_label( $id );
			}
		} else {
			if ( $id <= 0 ) {
				$id = (int) get_the_ID();
			}
			$level = TransparAI_Meta::get_content_level( $id );
			if ( ! TransparAI_Meta::level_is_ai( $level ) ) {
				return '';
			}
			if ( '' === $text ) {
				$text = self::text( $id, $level );
			}
		}

		return self::render(
			array(
				'text'    => $text,
				'variant' => (string) $atts['style'],
				'type'    => $type,
			)
		);
	}

	/**
	 * Register the server-rendered block from its block.json.
	 */
	public static function register_block(): void {
		if ( ! function_exists( 'register_block_type' ) ) {
			return;
		}
		register_block_type(
			TRANSPARAI_PLUGIN_DIR . 'blocks/notice',
			array( 'render_callback' => array( self::class, 'render_block' ) )
		);
	}

	/**
	 * Block output. Server-rendered so a wording change in the settings
	 * applies to every placed block at once.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @param string               $content    Inner content (unused).
	 * @param WP_Block|null        $block      Block instance with context.
	 */
	public static function render_block( array $attributes, string $content = '', $block = null ): string {
		$post_id = isset( $block->context['postId'] ) ? (int) $block->context['postId'] : (int) get_the_ID();
		$text    = sanitize_text_field( (string) ( $attributes['text'] ?? '' ) );
		$level   = TransparAI_Meta::get_content_level( $post_id );

		if ( ! TransparAI_Meta::level_is_ai( $level ) ) {
			/* Editor preview only: say why nothing shows instead of rendering an empty block. */
			if ( defined( 'REST_REQUEST' ) && REST_REQUEST && current_user_can( 'edit_post', $post_id ) ) {
				return '<div class="' . esc_attr( self::MARKER . '-empty' ) . '">' . esc_html__( 'This post has no AI level yet, so the notice stays hidden. Set the level in the document sidebar under TransparAI.', 'transparai' ) . '</div>';
			}
			return '';
		}
		if ( '' === $text ) {
			$text = self::text( $post_id, $level );
		}

		$wrapper = function_exists( 'get_block_wrapper_attributes' ) ? get_block_wrapper_attributes() : '';
		$class   = '';
		if ( preg_match( '/class="([^"]*)"/', $wrapper, $m ) ) {
			$class = $m[1];
		}
		return self::render(
			array(
				'text'    => $text,
				'variant' => (string) ( $attributes['variant'] ?? 'block' ),
				'class'   => $class,
			)
		);
	}

	/**
	 * Strings for the block's editor script (no JSON translation files needed).
	 */
	public static function localize_block_editor(): void {
		wp_localize_script(
			'transparai-notice-editor-script',
			'transparaiNotice',
			array(
				'title'       => __( 'AI notice', 'transparai' ),
				'variant'     => __( 'Style', 'transparai' ),
				'block'       => __( 'Block (own line)', 'transparai' ),
				'inline'      => __( 'Inline (inside text)', 'transparai' ),
				'text'        => __( 'Custom text', 'transparai' ),
				'textHelp'    => __( 'Leave empty to use the wording from the TransparAI settings.', 'transparai' ),
				'placeholder' => __( 'AI notice', 'transparai' ),
			)
		);
	}

	/* ---------------------------------------------------------------------
	 * Structured data
	 * ------------------------------------------------------------------- */

	/**
	 * JSON-LD node for a post whose text is AI-written, or null. Same shape
	 * as the media nodes: digitalSourceType is defined for CreativeWork in
	 * general, so a machine reading the page learns one convention.
	 *
	 * @return array<string, mixed>|null
	 */
	public static function schema_node( int $post_id ): ?array {
		$level = TransparAI_Meta::get_content_level( $post_id );
		if ( ! TransparAI_Meta::level_is_ai( $level ) ) {
			return null;
		}
		$url = (string) get_permalink( $post_id );
		if ( '' === $url ) {
			return null;
		}
		$type = 'Article';
		if ( 'page' === get_post_type( $post_id ) ) {
			$type = 'WebPage';
		}
		/* Assisted text is a human/AI mix; the composite token is the honest fit. */
		$token = TransparAI_Meta::LEVEL_ASSISTED === $level ? TransparAI_Meta::DST_COMPOSITE : TransparAI_Meta::DST_TRAINED;
		$node  = array_merge(
			array(
				'@type'    => $type,
				'@id'      => $url . '#transparai',
				'url'      => $url,
				'headline' => (string) get_the_title( $post_id ),
			),
			TransparAI_Meta::dst_schema( $token )
		);
		if ( TransparAI_Meta::LEVEL_REVIEWED === $level && TransparAI_Options::enabled( 'content_show_reviewer' ) ) {
			$stamp = TransparAI_Meta::content_review( $post_id );
			$name  = null === $stamp ? '' : ( '' !== $stamp['responsible'] ? $stamp['responsible'] : $stamp['by'] );
			if ( '' !== $name ) {
				$node['reviewedBy'] = array(
					'@type' => 'Person',
					'name'  => $name,
				);
			}
		}
		return $node;
	}
}
