<?php
/**
 * Context integrations: attachments generated by AI plugins on this site are
 * labeled at the source — no file metadata needed.
 *
 * Watched producers:
 *  - AI Engine        (post meta `_mwai_purpose` = 'generated' / `mwai_model`)
 *  - AI Power         (post meta `_aipkit_generated_image` = '1')
 *  - WordPress AI     (post meta `ai_generated` = '1')
 *  - Elementor AI     (upload during the `ai_upload_image` AJAX action)
 *
 * Public API for any other producer:
 *  do_action( 'transparai_mark_ai', $attachment_id, 'My Generator' );
 *
 * @package TransparAI
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Third-party context marking.
 */
final class TransparAI_Integrations {

	/**
	 * Register hooks.
	 */
	public static function init(): void {
		add_action( 'added_post_meta', array( self::class, 'on_foreign_meta' ), 10, 4 );
		add_action( 'updated_post_meta', array( self::class, 'on_foreign_meta' ), 10, 4 );
		add_action( 'add_attachment', array( self::class, 'on_upload_context' ), 15 );
		add_action( 'transparai_mark_ai', array( self::class, 'mark' ), 10, 2 );
	}

	/**
	 * Watch meta written by known AI producer plugins.
	 *
	 * @param int|int[] $meta_id    Meta ID(s).
	 * @param int       $object_id  Post ID.
	 * @param string    $meta_key   Meta key.
	 * @param mixed     $meta_value Meta value.
	 */
	public static function on_foreign_meta( $meta_id, $object_id, $meta_key, $meta_value ): void {
		$object_id = (int) $object_id;
		if ( 'attachment' !== get_post_type( $object_id ) ) {
			return;
		}

		$generator = '';
		if ( '_mwai_purpose' === $meta_key && 'generated' === $meta_value ) {
			$generator = 'AI Engine';
		} elseif ( 'mwai_model' === $meta_key && is_string( $meta_value ) && '' !== $meta_value ) {
			$generator = 'AI Engine (' . sanitize_text_field( $meta_value ) . ')';
		} elseif ( '_aipkit_generated_image' === $meta_key && '1' === (string) $meta_value ) {
			$generator = 'AI Power';
		} elseif ( 'ai_generated' === $meta_key && '1' === (string) $meta_value ) {
			$generator = 'WordPress AI';
		}

		if ( '' !== $generator ) {
			self::mark( $object_id, $generator );
		}
	}

	/**
	 * Elementor AI uploads run through a dedicated AJAX action.
	 */
	public static function on_upload_context( int $attachment_id ): void {
		if ( ! wp_doing_ajax() ) {
			return;
		}
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- read-only context sniff of a foreign AJAX action; no state change based on user input.
		$action = isset( $_REQUEST['action'] ) ? sanitize_key( wp_unslash( (string) $_REQUEST['action'] ) ) : '';
		if ( 'ai_upload_image' === $action ) {
			self::mark( $attachment_id, 'Elementor AI' );
		}
	}

	/**
	 * Mark an attachment as AI-generated from producer context.
	 *
	 * @param int    $attachment_id Attachment ID.
	 * @param string $generator     Producer label.
	 */
	public static function mark( $attachment_id, $generator = '' ): void {
		$attachment_id = (int) $attachment_id;
		if ( ! $attachment_id || 'attachment' !== get_post_type( $attachment_id ) ) {
			return;
		}
		if ( TransparAI_Meta::is_flagged( $attachment_id ) ) {
			return;
		}

		TransparAI_Meta::store_result(
			$attachment_id,
			array(
				'type'       => 'generated',
				'source'     => 'context',
				'generator'  => (string) $generator,
				'confidence' => 'certain',
				'evidence'   => 'Generated on this site' . ( '' !== $generator ? ' by ' . $generator : '' ),
			)
		);
		TransparAI_Meta::flag( $attachment_id, 'context' );
	}
}
