<?php
/**
 * Disclosure notice: wording per level, the automatic note with its guards
 * and double-output protection, shortcode honesty, feed variants and the
 * JSON-LD node.
 *
 * @package TransparAI
 */

declare( strict_types = 1 );

use PHPUnit\Framework\TestCase;

final class NoticeTest extends TestCase {

	protected function setUp(): void {
		trai_test_reset();
	}

	private function post( int $id, string $level, string $content = '<p>Body</p>' ): void {
		global $trai_test_posts, $trai_test_current_post;
		$post                   = new WP_Post();
		$post->ID               = $id;
		$post->post_title       = 'Post ' . $id;
		$post->post_content     = $content;
		$trai_test_posts[ $id ] = $post;
		$trai_test_current_post = $id;
		if ( '' !== $level ) {
			update_post_meta( $id, TransparAI_Meta::KEY_CONTENT_AI, $level );
		}
	}

	public function test_text_per_level_and_custom_override(): void {
		global $trai_test_options;
		$this->post( 1, 'none' );
		$this->assertSame( '', TransparAI_Notice::text( 1 ), 'No AI means no note' );

		$this->post( 2, 'assisted' );
		$this->assertSame( 'This text was created with the help of AI.', TransparAI_Notice::text( 2 ) );
		$this->post( 3, '1' );
		$this->assertSame( 'This text was generated by AI.', TransparAI_Notice::text( 3 ), 'Legacy checkbox value reads as generated' );

		$trai_test_options['transparai_settings'] = array( 'content_notice_text' => 'Custom wording' );
		$this->assertSame( 'Custom wording', TransparAI_Notice::text( 2 ) );
	}

	public function test_reviewer_is_named_only_when_enabled(): void {
		global $trai_test_options;
		$this->post( 5, 'generated_reviewed' );
		update_post_meta( 5, TransparAI_Meta::KEY_CONTENT_REVIEW, wp_json_encode( array( 'by' => 'Eva', 'by_id' => 2, 'on' => '2026-09-14', 'responsible' => 'Jane', 'hash' => 'x' ) ) );

		$this->assertStringNotContainsString( 'Jane', TransparAI_Notice::text( 5 ) );

		$trai_test_options['transparai_settings'] = array( 'content_show_reviewer' => '1' );
		$this->assertStringContainsString( 'Reviewed by Jane on 2026-09-14.', TransparAI_Notice::text( 5 ) );
	}

	public function test_render_variants_and_escaping(): void {
		$block = TransparAI_Notice::render( array( 'text' => 'A <b>note</b>' ) );
		$this->assertStringStartsWith( '<div class="trai-notice trai-notice--block trai-notice--content" role="note">', $block );
		$this->assertStringContainsString( 'A &lt;b&gt;note&lt;/b&gt;', $block );

		$inline = TransparAI_Notice::render( array( 'text' => 'x', 'variant' => 'inline', 'type' => 'media' ) );
		$this->assertStringStartsWith( '<span class="trai-notice trai-notice--inline trai-notice--media"', $inline );

		$this->assertSame( '', TransparAI_Notice::render( array( 'text' => '  ' ) ) );
	}

	public function test_automatic_note_guards_and_position(): void {
		global $trai_test_options, $trai_test_blocks;
		$this->post( 20, '' );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ), 'Unclassified post stays untouched' );

		$this->post( 21, 'generated' );
		$out = TransparAI_Notice::filter_content( '<p>Body</p>' );
		$this->assertStringStartsWith( '<div class="trai-notice', $out );
		$this->assertStringEndsWith( '<p>Body</p>', $out );

		$trai_test_options['transparai_settings'] = array( 'content_notice_position' => 'after' );
		$this->assertStringStartsWith( '<p>Body</p><div class="trai-notice', TransparAI_Notice::filter_content( '<p>Body</p>' ) );

		/* A placed block or an already rendered note switches the automatic one off. */
		$trai_test_blocks[21] = array( TransparAI_Notice::BLOCK );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ) );
		$trai_test_blocks[21] = array();
		$placed               = '<p>Body</p><span class="trai-notice trai-notice--inline trai-notice--content" role="note">x</span>';
		$this->assertSame( $placed, TransparAI_Notice::filter_content( $placed ) );
	}

	public function test_shortcode_never_states_what_is_not_declared(): void {
		$this->post( 30, '' );
		$this->assertSame( '', TransparAI_Notice::shortcode( array() ), 'Post without level renders nothing' );
		$this->assertSame( '', TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77' ) ), 'Unlabeled media renders nothing' );

		$this->post( 31, 'assisted' );
		$out = TransparAI_Notice::shortcode( array( 'style' => 'inline' ) );
		$this->assertStringStartsWith( '<span class="trai-notice trai-notice--inline', $out );
		$this->assertStringContainsString( 'help of AI', $out );

		update_post_meta( 77, TransparAI_Meta::KEY_FLAG, '1' );
		$media = TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77' ) );
		$this->assertStringContainsString( 'trai-notice--media', $media );
		$this->assertStringContainsString( 'AI-generated', $media );
		$this->assertStringContainsString( 'Own text', TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77', 'text' => 'Own text' ) ) );
	}

	public function test_feed_variants_are_plain_and_switchable(): void {
		global $trai_test_options;
		$this->post( 40, 'generated' );
		$trai_test_options['transparai_settings'] = array( 'feed_notice' => '0' );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content_feed( '<p>Body</p>' ), 'Switched off' );

		$trai_test_options['transparai_settings'] = array();
		$this->assertSame( '<p>This text was generated by AI.</p><p>Body</p>', TransparAI_Notice::filter_content_feed( '<p>Body</p>' ), 'On by default: the in-page note skips feeds' );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt_rss( 'Teaser ' ) );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt_rss( 'Teaser This text was generated by AI.' ), 'No double append' );

		ob_start();
		TransparAI_Notice::rss_item();
		$this->assertSame( "\t\t<dc:description>This text was generated by AI.</dc:description>\n", ob_get_clean() );
	}

	public function test_excerpt_note_is_opt_in(): void {
		global $trai_test_options;
		$this->post( 41, 'generated' );
		$this->assertSame( 'Teaser', TransparAI_Notice::filter_excerpt( 'Teaser' ) );
		$trai_test_options['transparai_settings'] = array( 'content_excerpt_notice' => '1' );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt( 'Teaser' ) );
	}

	public function test_schema_node_uses_both_vocabularies(): void {
		$this->post( 50, 'assisted' );
		$node = TransparAI_Notice::schema_node( 50 );
		$this->assertIsArray( $node );
		$this->assertSame( 'Article', $node['@type'] );
		$this->assertSame( 'https://example.test/?p=50#transparai', $node['@id'] );
		$this->assertSame( 'https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource', $node['digitalSourceType'] );
		$this->assertSame( 'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia', $node['additionalProperty']['value'] );
		$this->assertArrayNotHasKey( 'reviewedBy', $node );

		$this->post( 51, 'none' );
		$this->assertNull( TransparAI_Notice::schema_node( 51 ) );
	}


	public function test_new_variants_render_the_right_markup(): void {
		$banner = TransparAI_Notice::render( array( 'text' => 'Banner', 'variant' => 'banner' ) );
		$this->assertStringStartsWith( '<div class="trai-notice trai-notice--banner trai-notice--content" role="note">', $banner );
		$this->assertStringContainsString( 'class="trai-notice-dismiss"', $banner );

		$badge = TransparAI_Notice::render( array( 'text' => 'Badge', 'variant' => 'badge' ) );
		$this->assertStringStartsWith( '<span class="trai-notice trai-notice--badge', $badge );

		$modal = TransparAI_Notice::render( array( 'text' => 'Modal <b>x</b>', 'variant' => 'modal' ) );
		$this->assertStringContainsString( '<dialog class="trai-notice-dialog"', $modal );
		$this->assertStringContainsString( 'Modal &lt;b&gt;x&lt;/b&gt;', $modal );
		$this->assertStringContainsString( 'class="trai-notice-open"', $modal );

		$this->assertStringStartsWith( '<div class="trai-notice trai-notice--block', TransparAI_Notice::render( array( 'text' => 'x', 'variant' => 'nonsense' ) ), 'Unknown variants fall back to block' );
		$this->assertStringContainsString( 'trai-notice--systems', TransparAI_Notice::render( array( 'text' => 'x', 'type' => 'systems' ) ) );
	}

	public function test_style_setting_and_both_position_drive_the_automatic_note(): void {
		global $trai_test_options;
		$this->post( 31, 'generated' );
		$trai_test_options['transparai_settings'] = array(
			'content_notice_style'    => 'banner',
			'content_notice_position' => 'both',
		);
		$out = TransparAI_Notice::filter_content( '<p>Body</p>' );
		$this->assertSame( 2, substr_count( $out, 'trai-notice--banner' ), 'Both sides carry the note' );
		$this->assertStringContainsString( 'role="note"', $out );

		$trai_test_options['transparai_settings']['feed_notice'] = '1';
		$feed = TransparAI_Notice::filter_content_feed( '<p>Body</p>' );
		$this->assertSame( 2, substr_count( $feed, '<p>This text was generated by AI.</p>' ) );
	}

	public function test_title_badge_and_feed_prefix_are_opt_in_and_guarded(): void {
		global $trai_test_options;
		$this->post( 41, 'generated' );
		$this->assertSame( 'Hello', TransparAI_Notice::filter_title( 'Hello', 41 ), 'Off by default' );

		$trai_test_options['transparai_settings'] = array( 'content_title_badge' => '1' );
		$this->assertSame( 'Hello', TransparAI_Notice::filter_title( 'Hello', 42 ), 'Another post id (menu item, widget) stays clean' );
		$this->assertSame( 'Hello', TransparAI_Notice::filter_title( 'Hello', 0 ) );

		$badged = TransparAI_Notice::filter_title( 'Hello', 41 );
		$this->assertStringStartsWith( 'Hello <span class="trai-notice trai-notice--badge trai-title-badge"', $badged );
		$this->assertSame( $badged, TransparAI_Notice::filter_title( $badged, 41 ), 'Never doubled' );

		$this->post( 43, 'none' );
		$this->assertSame( 'Plain', TransparAI_Notice::filter_title( 'Plain', 43 ) );

		$this->post( 44, 'assisted' );
		$this->assertSame( 'Feed', TransparAI_Notice::filter_title_rss( 'Feed' ), 'Prefix is opt-in' );
		$trai_test_options['transparai_settings']['feed_title_prefix'] = '1';
		$this->assertSame( '[AI] Feed', TransparAI_Notice::filter_title_rss( 'Feed' ) );
		$this->assertSame( '[AI] Feed', TransparAI_Notice::filter_title_rss( '[AI] Feed' ) );
		$this->post( 45, 'none' );
		$this->assertSame( 'Feed', TransparAI_Notice::filter_title_rss( 'Feed' ) );
	}

	public function test_shortcode_passes_styles_and_renders_systems_only_when_visible(): void {
		global $trai_test_options;
		$this->post( 51, 'generated' );
		$this->assertStringStartsWith( '<div class="trai-notice trai-notice--banner', TransparAI_Notice::shortcode( array( 'style' => 'banner' ) ) );

		$this->assertSame( '', TransparAI_Notice::shortcode( array( 'type' => 'systems' ) ), 'No visible system, no text' );
		$id = TransparAI_Systems::declare( 'Recommender', 'personalisation' );
		TransparAI_Systems::set_visible( array( $id ) );
		$trai_test_options['transparai_settings'] = array( 'systems_notice' => '1' );
		$out = TransparAI_Notice::shortcode( array( 'type' => 'systems', 'style' => 'inline' ) );
		$this->assertStringContainsString( 'trai-notice--systems', $out );
		$this->assertStringContainsString( 'Recommender', $out );
	}

	private function block( string $name, array $attributes = array(), int $post_id = 0 ): string {
		$block          = new stdClass();
		$block->name    = $name;
		$block->context = $post_id > 0 ? array( 'postId' => $post_id ) : array();
		return TransparAI_Notice::render_block( $attributes, '', $block );
	}

	public function test_every_block_renders_only_what_is_declared(): void {
		global $trai_test_options;

		/* Text note: the block is the placement, the automatic note steps back. */
		$this->post( 70, 'generated' );
		$out = $this->block( 'transparai/notice', array( 'variant' => 'badge' ), 70 );
		$this->assertStringContainsString( 'trai-notice--badge', $out );
		$this->assertStringContainsString( 'trai-notice--content', $out );
		$this->assertStringContainsString( 'wp-block-transparai-notice', $out );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ), 'Placed by the block, no automatic note' );
		$this->post( 71, 'none' );
		$this->assertSame( '', $this->block( 'transparai/notice', array(), 71 ) );

		/* Media label: AI label, human declaration, nothing for the rest. */
		update_post_meta( 72, TransparAI_Meta::KEY_FLAG, '1' );
		$out = $this->block( 'transparai/media-label', array( 'id' => 72 ) );
		$this->assertStringContainsString( 'trai-notice--inline trai-notice--media', $out );
		$this->assertStringContainsString( 'AI-generated', $out );
		update_post_meta( 73, TransparAI_Meta::KEY_HUMAN, TransparAI_Meta::DST_CAPTURE );
		$this->assertStringContainsString( 'Human made', $this->block( 'transparai/media-label', array( 'id' => 73 ) ) );
		$this->assertSame( '', $this->block( 'transparai/media-label', array( 'id' => 74 ) ) );
		$this->assertSame( '', $this->block( 'transparai/media-label', array() ) );

		/* Chatbot: only when the operator said an AI answers. */
		$trai_test_options['transparai_settings'] = array( 'chatbot_answer' => 'yes', 'chatbot_staffing' => 'human' );
		$this->assertSame( '', $this->block( 'transparai/chatbot-notice' ) );
		$this->assertSame( '', TransparAI_Notice::shortcode( array( 'type' => 'chatbot' ) ) );
		$trai_test_options['transparai_settings']['chatbot_staffing'] = 'ai';
		$out = $this->block( 'transparai/chatbot-notice', array( 'variant' => 'inline' ) );
		$this->assertStringContainsString( 'trai-notice--inline trai-notice--chatbot', $out );
		$this->assertStringContainsString( 'You are chatting with an AI system.', $out );
		$this->assertStringContainsString( 'trai-notice--chatbot', TransparAI_Notice::shortcode( array( 'type' => 'chatbot' ) ) );

		/* Systems: sentence and list from the same visible set. */
		$this->assertSame( '', $this->block( 'transparai/systems-notice' ) );
		$this->assertSame( '', $this->block( 'transparai/systems-list' ) );
		$id = TransparAI_Systems::declare( 'Recommender', 'personalisation' );
		TransparAI_Systems::set_visible( array( $id ) );
		$trai_test_options['transparai_settings']['systems_notice'] = '1';
		$this->assertStringContainsString( 'Recommender', $this->block( 'transparai/systems-notice', array( 'variant' => 'banner' ) ) );
		$list = $this->block( 'transparai/systems-list' );
		$this->assertStringStartsWith( '<ul class="wp-block-transparai-notice', $list );
		$this->assertStringContainsString( '<strong>Recommender</strong> <span class="trai-systems-list-category">Personalisation</span>', $list );
	}

	public function test_manual_placement_switches_the_automatic_outputs_off(): void {
		global $trai_test_options;
		$this->post( 80, 'generated' );
		$trai_test_options['transparai_settings'] = array( 'content_notice_position' => 'manual' );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ) );
		$this->assertStringContainsString( 'trai-notice--content', TransparAI_Notice::shortcode( array() ), 'The shortcode still renders' );

		$id = TransparAI_Systems::declare( 'Recommender', 'personalisation' );
		TransparAI_Systems::set_visible( array( $id ) );
		$trai_test_options['transparai_settings']['systems_notice'] = '1';
		$trai_test_options['transparai_settings']['systems_notice_style'] = 'manual';
		ob_start();
		TransparAI_Systems::print_notice();
		$this->assertSame( '', ob_get_clean(), 'Manual: no badge or banner' );
		$this->assertSame( array(), TransparAI_Systems::footer_notice( array() ), 'Manual: no footer line' );
		$trai_test_options['transparai_settings']['systems_notice_style'] = 'footer';
		$this->assertStringContainsString( 'Recommender', TransparAI_Systems::footer_notice( array() )['systems'] );
	}
}
