<?php
/**
 * Disclosure notice: wording per level, the automatic note with its guards
 * and double-output protection, shortcode honesty, feed variants and the
 * JSON-LD node.
 *
 * @package TransparAI
 */

declare( strict_types = 1 );

use PHPUnit\Framework\TestCase;

final class NoticeTest extends TestCase {

	protected function setUp(): void {
		trai_test_reset();
	}

	private function post( int $id, string $level, string $content = '<p>Body</p>' ): void {
		global $trai_test_posts, $trai_test_current_post;
		$post                   = new WP_Post();
		$post->ID               = $id;
		$post->post_title       = 'Post ' . $id;
		$post->post_content     = $content;
		$trai_test_posts[ $id ] = $post;
		$trai_test_current_post = $id;
		if ( '' !== $level ) {
			update_post_meta( $id, TransparAI_Meta::KEY_CONTENT_AI, $level );
		}
	}

	public function test_text_per_level_and_custom_override(): void {
		global $trai_test_options;
		$this->post( 1, 'none' );
		$this->assertSame( '', TransparAI_Notice::text( 1 ), 'No AI means no note' );

		$this->post( 2, 'assisted' );
		$this->assertSame( 'This text was created with the help of AI.', TransparAI_Notice::text( 2 ) );
		$this->post( 3, '1' );
		$this->assertSame( 'This text was generated by AI.', TransparAI_Notice::text( 3 ), 'Legacy checkbox value reads as generated' );

		$trai_test_options['transparai_settings'] = array( 'content_notice_text' => 'Custom wording' );
		$this->assertSame( 'Custom wording', TransparAI_Notice::text( 2 ) );
	}

	public function test_reviewer_is_named_only_when_enabled(): void {
		global $trai_test_options;
		$this->post( 5, 'generated_reviewed' );
		update_post_meta( 5, TransparAI_Meta::KEY_CONTENT_REVIEW, wp_json_encode( array( 'by' => 'Eva', 'by_id' => 2, 'on' => '2026-09-14', 'responsible' => 'Jane', 'hash' => 'x' ) ) );

		$this->assertStringNotContainsString( 'Jane', TransparAI_Notice::text( 5 ) );

		$trai_test_options['transparai_settings'] = array( 'content_show_reviewer' => '1' );
		$this->assertStringContainsString( 'Reviewed by Jane on 2026-09-14.', TransparAI_Notice::text( 5 ) );
	}

	public function test_render_variants_and_escaping(): void {
		$block = TransparAI_Notice::render( array( 'text' => 'A <b>note</b>' ) );
		$this->assertStringStartsWith( '<div class="trai-notice trai-notice--block trai-notice--content" role="note">', $block );
		$this->assertStringContainsString( 'A &lt;b&gt;note&lt;/b&gt;', $block );

		$inline = TransparAI_Notice::render( array( 'text' => 'x', 'variant' => 'inline', 'type' => 'media' ) );
		$this->assertStringStartsWith( '<span class="trai-notice trai-notice--inline trai-notice--media"', $inline );

		$this->assertSame( '', TransparAI_Notice::render( array( 'text' => '  ' ) ) );
	}

	public function test_automatic_note_guards_and_position(): void {
		global $trai_test_options, $trai_test_blocks;
		$this->post( 20, '' );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ), 'Unclassified post stays untouched' );

		$this->post( 21, 'generated' );
		$out = TransparAI_Notice::filter_content( '<p>Body</p>' );
		$this->assertStringStartsWith( '<div class="trai-notice', $out );
		$this->assertStringEndsWith( '<p>Body</p>', $out );

		$trai_test_options['transparai_settings'] = array( 'content_notice_position' => 'after' );
		$this->assertStringStartsWith( '<p>Body</p><div class="trai-notice', TransparAI_Notice::filter_content( '<p>Body</p>' ) );

		/* A placed block or an already rendered note switches the automatic one off. */
		$trai_test_blocks[21] = array( TransparAI_Notice::BLOCK );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content( '<p>Body</p>' ) );
		$trai_test_blocks[21] = array();
		$placed               = '<p>Body</p><span class="trai-notice trai-notice--inline trai-notice--content" role="note">x</span>';
		$this->assertSame( $placed, TransparAI_Notice::filter_content( $placed ) );
	}

	public function test_shortcode_never_states_what_is_not_declared(): void {
		$this->post( 30, '' );
		$this->assertSame( '', TransparAI_Notice::shortcode( array() ), 'Post without level renders nothing' );
		$this->assertSame( '', TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77' ) ), 'Unlabeled media renders nothing' );

		$this->post( 31, 'assisted' );
		$out = TransparAI_Notice::shortcode( array( 'style' => 'inline' ) );
		$this->assertStringStartsWith( '<span class="trai-notice trai-notice--inline', $out );
		$this->assertStringContainsString( 'help of AI', $out );

		update_post_meta( 77, TransparAI_Meta::KEY_FLAG, '1' );
		$media = TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77' ) );
		$this->assertStringContainsString( 'trai-notice--media', $media );
		$this->assertStringContainsString( 'AI-generated', $media );
		$this->assertStringContainsString( 'Own text', TransparAI_Notice::shortcode( array( 'type' => 'media', 'id' => '77', 'text' => 'Own text' ) ) );
	}

	public function test_feed_variants_are_plain_and_opt_in(): void {
		global $trai_test_options;
		$this->post( 40, 'generated' );
		$this->assertSame( '<p>Body</p>', TransparAI_Notice::filter_content_feed( '<p>Body</p>' ), 'Off by default' );

		$trai_test_options['transparai_settings'] = array( 'feed_notice' => '1' );
		$this->assertSame( '<p>This text was generated by AI.</p><p>Body</p>', TransparAI_Notice::filter_content_feed( '<p>Body</p>' ) );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt_rss( 'Teaser ' ) );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt_rss( 'Teaser This text was generated by AI.' ), 'No double append' );

		ob_start();
		TransparAI_Notice::rss_item();
		$this->assertSame( "\t\t<dc:description>This text was generated by AI.</dc:description>\n", ob_get_clean() );
	}

	public function test_excerpt_note_is_opt_in(): void {
		global $trai_test_options;
		$this->post( 41, 'generated' );
		$this->assertSame( 'Teaser', TransparAI_Notice::filter_excerpt( 'Teaser' ) );
		$trai_test_options['transparai_settings'] = array( 'content_excerpt_notice' => '1' );
		$this->assertSame( 'Teaser This text was generated by AI.', TransparAI_Notice::filter_excerpt( 'Teaser' ) );
	}

	public function test_schema_node_uses_both_vocabularies(): void {
		$this->post( 50, 'assisted' );
		$node = TransparAI_Notice::schema_node( 50 );
		$this->assertIsArray( $node );
		$this->assertSame( 'Article', $node['@type'] );
		$this->assertSame( 'https://example.test/?p=50#transparai', $node['@id'] );
		$this->assertSame( 'https://schema.org/CompositeWithTrainedAlgorithmicMediaDigitalSource', $node['digitalSourceType'] );
		$this->assertSame( 'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia', $node['additionalProperty']['value'] );
		$this->assertArrayNotHasKey( 'reviewedBy', $node );

		$this->post( 51, 'none' );
		$this->assertNull( TransparAI_Notice::schema_node( 51 ) );
	}
}
